import { spawn } from "node:child_process";

export interface DeliverParams {
  workDir: string;
  requirement: string;
  workflowRunId: string;
  reviewReport?: string;
}

export interface DeliverResult {
  prUrl?: string;
  branch?: string;
  error?: string;
}

let ghAvailable: boolean | null = null;

export class DeliveryManager {
  shouldDeliver(triggerType: string, mode: "local" | "cloned"): boolean {
    return triggerType === "manual" && mode === "cloned" && ghAvailable === true;
  }

  async checkGhAvailability(): Promise<void> {
    ghAvailable = await isInPath("gh");
  }

  async deliver(params: DeliverParams): Promise<DeliverResult> {
    const shortId = params.workflowRunId.slice(0, 8);
    let branch = `ai-sdlc/${shortId}`;

    try {
      try {
        await execGit(["checkout", "-b", branch], params.workDir);
      } catch {
        branch = `ai-sdlc/${shortId}-${Date.now()}`;
        await execGit(["checkout", "-b", branch], params.workDir);
      }

      await execGit(["add", "-A"], params.workDir);

      const title = params.requirement.slice(0, 60);
      await execGit(["commit", "-m", `feat: ${title}`], params.workDir);
      await execGit(["push", "-u", "origin", branch], params.workDir);

      const body = params.reviewReport
        ? `## AI Review\n\n${params.reviewReport.slice(0, 2000)}`
        : `Auto-generated by AI SDLC Platform\n\nWorkflow: ${params.workflowRunId}`;

      const prUrl = await execOutput("gh", ["pr", "create", "--title", title, "--body", body, "--head", branch], params.workDir);

      return { prUrl: prUrl.trim(), branch };
    } catch (err: any) {
      return { branch, error: err.message ?? String(err) };
    }
  }
}

async function isInPath(cmd: string): Promise<boolean> {
  return new Promise((resolve) => {
    const proc = spawn("which", [cmd], { stdio: ["ignore", "ignore", "ignore"] });
    proc.on("close", (code) => resolve(code === 0));
    proc.on("error", () => resolve(false));
  });
}

function execGit(args: string[], cwd: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const proc = spawn("git", args, { cwd, stdio: ["ignore", "ignore", "pipe"] });
    let stderr = "";
    proc.stderr?.on("data", (d) => { stderr += d; });
    proc.on("close", (code) => code === 0 ? resolve() : reject(new Error(`git ${args[0]} failed: ${stderr}`)));
    proc.on("error", reject);
  });
}

function execOutput(cmd: string, args: string[], cwd: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const proc = spawn(cmd, args, { cwd, stdio: ["ignore", "pipe", "pipe"] });
    let stdout = "", stderr = "";
    proc.stdout.on("data", (d) => { stdout += d; });
    proc.stderr?.on("data", (d) => { stderr += d; });
    proc.on("close", (code) => code === 0 ? resolve(stdout) : reject(new Error(`${cmd} failed: ${stderr}`)));
    proc.on("error", reject);
  });
}

export function resetGhCache(): void {
  ghAvailable = null;
}
